import "server-only";

import { and, asc, desc, eq, inArray, lt, sql } from "drizzle-orm";

import { db } from "@/lib/db";
import {
  clients,
  invoiceLineItems,
  invoices,
  jobs,
  payments,
  serviceTypes,
  sites,
  type InvoiceStatus,
} from "@db/schema";
import { newId } from "@/lib/ids";
import { recordAudit } from "@/lib/data/audit";
import { assertTenant, tenantFilter, type Scope } from "@/lib/data/scope";

const OPEN_STATUSES: InvoiceStatus[] = ["issued", "part_paid", "overdue"];

export async function listInvoices(scope: Scope, clientId?: string) {
  return db
    .select({
      id: invoices.id,
      number: invoices.number,
      clientId: invoices.clientId,
      clientName: clients.name,
      amount: invoices.amount,
      currency: invoices.currency,
      status: invoices.status,
      dueDate: invoices.dueDate,
      issuedAt: invoices.issuedAt,
      paidAt: invoices.paidAt,
      paidAmount: sql<number>`coalesce((select sum(${payments.amount}) from ${payments} where ${payments.invoiceId} = ${invoices.id}), 0)`,
    })
    .from(invoices)
    .innerJoin(clients, eq(invoices.clientId, clients.id))
    .where(
      and(
        tenantFilter(invoices.clientId, scope),
        clientId ? eq(invoices.clientId, clientId) : undefined,
        // Drafts are an internal working state; clients only see issued docs.
        scope.clientId ? inArray(invoices.status, [...OPEN_STATUSES, "paid"]) : undefined,
      ),
    )
    .orderBy(desc(invoices.issuedAt), desc(invoices.createdAt));
}

export async function getInvoice(scope: Scope, invoiceId: string) {
  const [row] = await db
    .select({
      id: invoices.id,
      number: invoices.number,
      clientId: invoices.clientId,
      clientName: clients.name,
      billingContact: clients.billingContact,
      billingEmail: clients.billingEmail,
      amount: invoices.amount,
      currency: invoices.currency,
      status: invoices.status,
      dueDate: invoices.dueDate,
      issuedAt: invoices.issuedAt,
      paidAt: invoices.paidAt,
      notes: invoices.notes,
    })
    .from(invoices)
    .innerJoin(clients, eq(invoices.clientId, clients.id))
    .where(eq(invoices.id, invoiceId))
    .limit(1);

  const invoice = assertTenant(scope, row, "invoice");
  if (!invoice) return undefined;
  if (scope.clientId && invoice.status === "draft") return undefined;

  const lines = await db
    .select({
      id: invoiceLineItems.id,
      description: invoiceLineItems.description,
      quantity: invoiceLineItems.quantity,
      unitAmount: invoiceLineItems.unitAmount,
      amount: invoiceLineItems.amount,
      jobReference: jobs.reference,
    })
    .from(invoiceLineItems)
    .leftJoin(jobs, eq(invoiceLineItems.jobId, jobs.id))
    .where(eq(invoiceLineItems.invoiceId, invoiceId));

  const paymentRows = await db
    .select()
    .from(payments)
    .where(eq(payments.invoiceId, invoiceId))
    .orderBy(asc(payments.receivedAt));

  return { ...invoice, lines, payments: paymentRows };
}

/**
 * Builds a draft invoice from every completed-but-unbilled job for a client.
 * Line amounts come from the service type's default rate.
 */
export async function generateInvoiceFromJobs(scope: Scope, clientId: string) {
  if (scope.clientId) throw new Error("Invoices are generated by Ecohygiene staff only");

  const billable = await db
    .select({
      jobId: jobs.id,
      reference: jobs.reference,
      completedAt: jobs.completedAt,
      siteName: sites.name,
      serviceName: serviceTypes.name,
      rate: serviceTypes.defaultRate,
    })
    .from(jobs)
    .innerJoin(sites, eq(jobs.siteId, sites.id))
    .innerJoin(serviceTypes, eq(jobs.serviceTypeId, serviceTypes.id))
    .where(
      and(
        eq(jobs.clientId, clientId),
        inArray(jobs.status, ["completed", "signed_off"]),
        sql`${jobs.billedInvoiceId} is null`,
      ),
    );

  if (billable.length === 0) return null;

  const [client] = await db
    .select({ terms: clients.paymentTermsDays })
    .from(clients)
    .where(eq(clients.id, clientId))
    .limit(1);

  const id = newId("inv");
  const total = billable.reduce((sum, job) => sum + job.rate, 0);
  const now = new Date();
  const [{ value: existing }] = await db.select({ value: sql<number>`count(*)` }).from(invoices);

  await db.insert(invoices).values({
    id,
    number: `INV-${now.getFullYear()}-${String(existing + 1).padStart(4, "0")}`,
    clientId,
    amount: total,
    status: "draft",
    dueDate: new Date(now.getTime() + (client?.terms ?? 30) * 24 * 60 * 60 * 1000),
  });

  for (const job of billable) {
    await db.insert(invoiceLineItems).values({
      id: newId("ili"),
      invoiceId: id,
      jobId: job.jobId,
      description: `${job.serviceName} — ${job.siteName} (${job.reference})`,
      quantity: 1,
      unitAmount: job.rate,
      amount: job.rate,
    });
    await db.update(jobs).set({ billedInvoiceId: id }).where(eq(jobs.id, job.jobId));
  }

  await recordAudit(scope, "invoice.generate", "invoice", id, { clientId, jobs: billable.length });
  return id;
}

export async function setInvoiceStatus(scope: Scope, invoiceId: string, status: InvoiceStatus) {
  if (scope.clientId) throw new Error("Clients cannot change invoice status");
  await db
    .update(invoices)
    .set({
      status,
      issuedAt: status === "issued" ? new Date() : undefined,
      paidAt: status === "paid" ? new Date() : undefined,
    })
    .where(eq(invoices.id, invoiceId));
  await recordAudit(scope, `invoice.${status}`, "invoice", invoiceId, {});
}

export async function recordPayment(
  scope: Scope,
  invoiceId: string,
  amount: number,
  method: "bank_transfer" | "mobile_money" | "cash" | "cheque",
  reference?: string,
) {
  if (scope.clientId) throw new Error("Clients cannot record payments");

  await db.insert(payments).values({
    id: newId("pay"),
    invoiceId,
    amount,
    method,
    reference: reference ?? null,
    receivedAt: new Date(),
    recordedBy: scope.userId === "system" ? null : scope.userId,
  });

  const [totals] = await db
    .select({
      invoiceAmount: invoices.amount,
      paid: sql<number>`coalesce((select sum(${payments.amount}) from ${payments} where ${payments.invoiceId} = ${invoices.id}), 0)`,
    })
    .from(invoices)
    .where(eq(invoices.id, invoiceId))
    .limit(1);

  if (totals) {
    const settled = totals.paid >= totals.invoiceAmount;
    await db
      .update(invoices)
      .set({ status: settled ? "paid" : "part_paid", paidAt: settled ? new Date() : null })
      .where(eq(invoices.id, invoiceId));
  }

  await recordAudit(scope, "invoice.payment", "invoice", invoiceId, { amount, method });
}

/** Flips issued invoices past their due date to `overdue`. */
export async function markOverdueInvoices(scope: Scope) {
  const result = await db
    .update(invoices)
    .set({ status: "overdue" })
    .where(and(inArray(invoices.status, ["issued", "part_paid"]), lt(invoices.dueDate, new Date())));
  await recordAudit(scope, "invoice.sweep_overdue", "invoice", null, {});
  return result;
}

export async function financeSummary(scope: Scope) {
  const [row] = await db
    .select({
      outstanding: sql<number>`coalesce(sum(case when ${invoices.status} in ('issued','part_paid','overdue') then ${invoices.amount} else 0 end), 0)`,
      overdue: sql<number>`coalesce(sum(case when ${invoices.status} = 'overdue' then ${invoices.amount} else 0 end), 0)`,
      paidThisMonth: sql<number>`coalesce(sum(case when ${invoices.status} = 'paid' and ${invoices.paidAt} >= ${startOfMonth().getTime()} then ${invoices.amount} else 0 end), 0)`,
      overdueCount: sql<number>`sum(case when ${invoices.status} = 'overdue' then 1 else 0 end)`,
    })
    .from(invoices)
    .where(tenantFilter(invoices.clientId, scope));

  return {
    outstanding: row?.outstanding ?? 0,
    overdue: row?.overdue ?? 0,
    paidThisMonth: row?.paidThisMonth ?? 0,
    overdueCount: row?.overdueCount ?? 0,
  };
}

function startOfMonth(): Date {
  const d = new Date();
  return new Date(d.getFullYear(), d.getMonth(), 1);
}
